---
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
extends:
  - "plugin:@typescript-eslint/recommended"
  - eslint-config-prettier
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
rules:
  "@typescript-eslint/no-unused-vars":
    - warn
    - argsIgnorePattern: "^_"
  no-use-before-define:
    - warn
  "@typescript-eslint/no-use-before-define":
    - warn
  no-unused-expressions:
    - error
  no-underscore-dangle:
    - error
  one-var:
    - error
    - never
  class-methods-use-this:
    - error
